# Generated by Django 4.0.4 on 2022-05-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
    ]
