# Generated by Django 4.0.4 on 2022-05-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_remove_imagemodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='nopixels',
            new_name='noobjects',
        ),
    ]
