# Generated by Django 4.0.4 on 2022-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_projectmodel_make_patches'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='train_ae',
            field=models.BooleanField(default=False),
        ),
    ]
