# Generated by Django 4.0.4 on 2022-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0006_projectmodel_train_ae'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='make_batches',
            field=models.BooleanField(default=False),
        ),
    ]
