# Generated by Django 4.0.4 on 2022-06-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0007_imagemodel_make_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='save_in_db',
            field=models.BooleanField(default=False),
        ),
    ]
