# Generated by Django 4.0.4 on 2022-06-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0009_imagemodel_superpixel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roismodel',
            name='imageROI',
        ),
        migrations.AddField(
            model_name='roismodel',
            name='roi_name',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='roismodel',
            name='roi_path',
            field=models.TextField(default='path'),
        ),
    ]
